import type {
  ChatChunkEvent,
  ChunkingSettings,
  ContextBounds,
  Conversation,
  DocumentRecord,
  Message,
  ModelCatalogEntry,
  ModelEvent,
  ModelFileInfo,
  ModelRole,
  ModelStatusSnapshot,
  RagProgressEvent,
  RetrievalSettings,
  SystemStats,
} from './types.js';

/** Unsubscribe handle returned by every `on*` registration. */
export type Unsubscribe = () => void;

/**
 * The single surface exposed to the renderer by `preload.cjs`.
 *
 * Every method is `ipcRenderer.invoke`-shaped: one serialisable argument
 * object, one promise. Long-running work returns immediately and reports
 * through the events, so a slow embedding never blocks the UI thread.
 */
export interface IpcApi {
  // ── Models ────────────────────────────────────────────────────────────────
  modelStatus(): Promise<ModelStatusSnapshot>;
  listModels(): Promise<ModelFileInfo[]>;
  modelCatalog(): Promise<ModelCatalogEntry[]>;
  selectModel(args: { role: ModelRole; fileName: string }): Promise<ModelStatusSnapshot>;
  deleteModel(args: { role: ModelRole; fileName: string }): Promise<ModelStatusSnapshot>;
  /**
   * Kick off a download; progress arrives on `onModelEvent`, and completion
   * arrives as a `status` event. Resolves once the file is on disk.
   */
  downloadModel(args: { role: ModelRole; url: string; fileName: string }): Promise<void>;
  /** Copy a `.gguf` the user already has into the managed models directory. */
  importModel(args: { role: ModelRole; path: string }): Promise<{ fileName: string }>;
  cancelDownload(args: { role: ModelRole }): Promise<void>;
  /** Measured limits for the context slider, derived from the model + free RAM. */
  contextBounds(args: { fileName?: string }): Promise<ContextBounds>;
  setContextSize(args: { contextSize: number }): Promise<ModelStatusSnapshot>;

  // ── Documents ─────────────────────────────────────────────────────────────
  listDocuments(): Promise<DocumentRecord[]>;
  /** Absolute paths, resolved to a `DocumentRecord` per accepted file. */
  addDocuments(args: { paths: string[] }): Promise<DocumentRecord[]>;
  setDocumentActive(args: { id: string; active: boolean }): Promise<DocumentRecord[]>;
  removeDocument(args: { id: string }): Promise<DocumentRecord[]>;
  /** Re-run chunking and embedding for one document, keeping its extraction. */
  reindexDocument(args: { id: string }): Promise<DocumentRecord>;
  getChunkingSettings(): Promise<ChunkingSettings>;
  setChunkingSettings(args: ChunkingSettings): Promise<ChunkingSettings>;

  // ── Retrieval ─────────────────────────────────────────────────────────────
  getRetrievalSettings(): Promise<RetrievalSettings>;
  setRetrievalSettings(args: RetrievalSettings): Promise<RetrievalSettings>;

  // ── Chat ──────────────────────────────────────────────────────────────────
  listConversations(): Promise<Conversation[]>;
  createConversation(): Promise<Conversation>;
  deleteConversation(args: { id: string }): Promise<Conversation[]>;
  renameConversation(args: { id: string; title: string }): Promise<Conversation[]>;
  loadMessages(args: { conversationId: string }): Promise<Message[]>;
  /**
   * Resolves when the turn is finished, not when it starts. `requestId` is
   * generated by the renderer so `stop` can address the right generation.
   */
  send(args: { conversationId: string; text: string; requestId: string }): Promise<void>;
  stop(args: { requestId: string }): Promise<void>;

  // ── Events ────────────────────────────────────────────────────────────────
  onModelEvent(cb: (event: ModelEvent) => void): Unsubscribe;
  onRagProgress(cb: (event: RagProgressEvent) => void): Unsubscribe;
  onChatChunk(cb: (event: ChatChunkEvent) => void): Unsubscribe;
  onSystemStats(cb: (stats: SystemStats) => void): Unsubscribe;
}

/**
 * Channel names, exported so `preload.cjs` and `ipc.ts` cannot drift apart.
 * The `.on` suffix marks renderer-directed push events rather than invocations.
 * Keyed by method name for the invoke channels, plus four push channels.
 */
export const Channels = {
  modelStatus: 'model:status',
  listModels: 'model:list',
  modelCatalog: 'model:catalog',
  selectModel: 'model:select',
  deleteModel: 'model:delete',
  downloadModel: 'model:download',
  importModel: 'model:import',
  cancelDownload: 'model:cancel-download',
  contextBounds: 'model:context-bounds',
  setContextSize: 'model:set-context-size',
  modelEvent: 'model:event.on',

  listDocuments: 'doc:list',
  addDocuments: 'doc:add',
  setDocumentActive: 'doc:set-active',
  removeDocument: 'doc:remove',
  reindexDocument: 'doc:reindex',
  getChunkingSettings: 'doc:get-chunking',
  setChunkingSettings: 'doc:set-chunking',
  ragProgress: 'rag:progress.on',

  getRetrievalSettings: 'rag:get-retrieval',
  setRetrievalSettings: 'rag:set-retrieval',

  listConversations: 'chat:list-conversations',
  createConversation: 'chat:create-conversation',
  deleteConversation: 'chat:delete-conversation',
  renameConversation: 'chat:rename-conversation',
  loadMessages: 'chat:load-messages',
  send: 'chat:send',
  stop: 'chat:stop',
  chatChunk: 'chat:chunk.on',

  systemStats: 'system:stats.on',
} as const;

/** Every channel `ipcMain` must have a handler for. */
export type InvokeChannel =
  (typeof Channels)[keyof typeof Channels] extends infer C
    ? C extends `${string}.on`
      ? never
      : C
    : never;
